CREATE TABLE ads (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL REFERENCES users(id),
    title VARCHAR(50) NOT NULL,
    description VARCHAR(240),
    PRIMARY KEY (id)
);